name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Run test 🧪
      run: ng test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.2.0
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_folder: dist/simple-app
        base_href: /leonce-tp2/
