name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Run test 🧪
      run: npm run test:coverages
    - name: Badge
      uses:  emibcn/clover-coverage-badges-action@v1
      with:
        coverage-clover-path: coverage/stslib/clover.xml
        coverage-summary-path: coverage/simple-app/coverage-summary.json
        github_token: ${{ secrets.ACCESS_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Run lint 🧪
      run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
    - uses: actions/checkout@v2
    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.2.0
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_folder: dist/simple-app
        base_href: /leonce-tp2/
